#!/usr/bin/env bash

PROJECTROOT=`echo $(cd ${0%/*}/../../ && pwd -P)`/
PHPUNIT="vendor/bin/phpunit"
FIXER="vendor/bin/php-cs-fixer"
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php$`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "------------------------------"
echo "Checking PHP Lint..."
echo "------------------------------"
for FILE in $SFILES
do
	php -l -d display_errors=0 ${PROJECTROOT}${FILE}
	if [ $? != 0 ]
	then
		echo "Fix the error in ${PROJECTROOT}${FILE} before commit."
		exit 1
	fi
	FILES="$FILES ${PROJECTROOT}${FILE}"
done


if [ "$FILES" != "" ]
then
	echo "------------------------------"
	echo "Running Code standard fixer..."
	echo "------------------------------"
    for FILE in $SFILES
    do
        php ${PROJECTROOT}${FIXER} fix $FILE -q
		git add $FILE
    done
else
	echo "no php file changed."
fi

php ${PHPUNIT}
if [ $? != 0 ]
then
    echo "Fix tests before commit."
    exit 1
fi
